CREATE TABLE funcionario (
    id INT (11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR (60) NOT NULL,
    senha VARCHAR (20) NOT NULL,
    email VARCHAR (120) NOT NULL UNIQUE,
    cpf VARCHAR (14) NOT NULL,
    endereco VARCHAR (80) NOT NULL
);
